services:
  webapp:
    image: project1_webapp_image
    container_name: project1_webapp_container
    build:
      context: .
      dockerfile: Dockerfile_webapp
    ports:
      - '3030:3000'
      - '9229:9229'
    volumes:
      - /test-project-bootstrap:/test-project-bootstrap
    user: usernew
    working_dir: /test-project-bootstrap
    links:
      - mongodb

  mongodb:
    image: project1_mongodb_image
    container_name: project1_mongodb_container
    build:
      context: .
      dockerfile: Dockerfile_mongodb
